//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MK.Accountancy.Blazor.Reports.Receipts.CollectionReceipts {
    
    public partial class CollectionReceipt : DevExpress.XtraReports.UI.XtraReport {
        private void InitializeComponent() {
            DevExpress.XtraReports.ReportInitializer reportInitializer = new DevExpress.XtraReports.ReportInitializer(this, "MK.Accountancy.Blazor.Reports.Receipts.CollectionReceipts.CollectionReceipt.vsrep" +
                    "x");

            // Controls
            this.TopMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.TopMarginBand>("TopMargin");
            this.BottomMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.BottomMarginBand>("BottomMargin");
            this.Detail = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("Detail");
            this.ReportHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportHeaderBand>("ReportHeader");
            this.DetailReport = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailReportBand>("DetailReport");
            this.GroupFooter1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.GroupFooterBand>("GroupFooter1");
            this.ReportFooter = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportFooterBand>("ReportFooter");
            this.table1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table1");
            this.tableRow1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow1");
            this.tableRow3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow3");
            this.tableRow2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow2");
            this.lblTitleReport = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("lblTitleReport");
            this.lblReceiptNo = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("lblReceiptNo");
            this.lbl1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("lbl1");
            this.txtReceiptNo = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("txtReceiptNo");
            this.lbl2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("lbl2");
            this.lblCurrentCodeName = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("lblCurrentCodeName");
            this.lbl3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("lbl3");
            this.tableCell5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell5");
            this.lblDate = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("lblDate");
            this.tableCell4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell4");
            this.txtDate = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("txtDate");
            this.tableCell3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell3");
            this.lblDeparment = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("lblDeparment");
            this.lbl4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("lbl4");
            this.txtDepartment = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("txtDepartment");
            this.Detail1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("Detail1");
            this.GroupHeader1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.GroupHeaderBand>("GroupHeader1");
            this.table3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table3");
            this.tableRow6 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow6");
            this.tableCell1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell1");
            this.tableCell2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell2");
            this.tableCell6 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell6");
            this.tableCell7 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell7");
            this.tableCell8 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell8");
            this.tableCell9 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell9");
            this.tableCell10 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell10");
            this.tableCell11 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell11");
            this.tableCell12 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell12");
            this.tableCell13 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell13");
            this.table2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table2");
            this.tableRow4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow4");
            this.tableRow5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow5");
            this.lblDetailTitle = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("lblDetailTitle");
            this.lblRowNo = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("lblRowNo");
            this.lblTrackingNo = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("lblTrackingNo");
            this.lblType = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("lblType");
            this.lblExpiryDate = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("lblExpiryDate");
            this.lblPrice = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("lblPrice");
            this.lblPrincipalDebtor = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("lblPrincipalDebtor");
            this.lblEndorser = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("lblEndorser");
            this.lblBankAndDeparment = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("lblBankAndDeparment");
            this.lblDocumentNo = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("lblDocumentNo");
            this.lblAccountNo = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("lblAccountNo");
            this.table4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table4");
            this.tableRow7 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow7");
            this.lblSums = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("lblSums");
            this.tableCell15 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell15");
            this.tableCell16 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell16");
            this.panel1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPanel>("panel1");
            this.lblPersonWhoCollected = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lblPersonWhoCollected");
            this.pageInfo1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageInfo>("pageInfo1");

            // Data Sources
            this.ObjectDataSource = reportInitializer.GetDataSource<DevExpress.DataAccess.ObjectBinding.ObjectDataSource>("ObjectDataSource");
            this.ObjectDataSource.DataSource = typeof(MK.Accountancy.Receipts.ReceiptReportDto);
        }
        private DevExpress.XtraReports.UI.TopMarginBand TopMargin;
        private DevExpress.XtraReports.UI.BottomMarginBand BottomMargin;
        private DevExpress.XtraReports.UI.DetailBand Detail;
        private DevExpress.XtraReports.UI.ReportHeaderBand ReportHeader;
        private DevExpress.XtraReports.UI.DetailReportBand DetailReport;
        private DevExpress.XtraReports.UI.GroupFooterBand GroupFooter1;
        private DevExpress.XtraReports.UI.ReportFooterBand ReportFooter;
        private DevExpress.XtraReports.UI.XRTable table1;
        private DevExpress.XtraReports.UI.XRTableRow tableRow1;
        private DevExpress.XtraReports.UI.XRTableRow tableRow3;
        private DevExpress.XtraReports.UI.XRTableRow tableRow2;
        private DevExpress.XtraReports.UI.XRTableCell lblTitleReport;
        private DevExpress.XtraReports.UI.XRTableCell lblReceiptNo;
        private DevExpress.XtraReports.UI.XRTableCell lbl1;
        private DevExpress.XtraReports.UI.XRTableCell txtReceiptNo;
        private DevExpress.XtraReports.UI.XRTableCell lbl2;
        private DevExpress.XtraReports.UI.XRTableCell lblCurrentCodeName;
        private DevExpress.XtraReports.UI.XRTableCell lbl3;
        private DevExpress.XtraReports.UI.XRTableCell tableCell5;
        private DevExpress.XtraReports.UI.XRTableCell lblDate;
        private DevExpress.XtraReports.UI.XRTableCell tableCell4;
        private DevExpress.XtraReports.UI.XRTableCell txtDate;
        private DevExpress.XtraReports.UI.XRTableCell tableCell3;
        private DevExpress.XtraReports.UI.XRTableCell lblDeparment;
        private DevExpress.XtraReports.UI.XRTableCell lbl4;
        private DevExpress.XtraReports.UI.XRTableCell txtDepartment;
        private DevExpress.XtraReports.UI.DetailBand Detail1;
        private DevExpress.XtraReports.UI.GroupHeaderBand GroupHeader1;
        private DevExpress.XtraReports.UI.XRTable table3;
        private DevExpress.XtraReports.UI.XRTableRow tableRow6;
        private DevExpress.XtraReports.UI.XRTableCell tableCell1;
        private DevExpress.XtraReports.UI.XRTableCell tableCell2;
        private DevExpress.XtraReports.UI.XRTableCell tableCell6;
        private DevExpress.XtraReports.UI.XRTableCell tableCell7;
        private DevExpress.XtraReports.UI.XRTableCell tableCell8;
        private DevExpress.XtraReports.UI.XRTableCell tableCell9;
        private DevExpress.XtraReports.UI.XRTableCell tableCell10;
        private DevExpress.XtraReports.UI.XRTableCell tableCell11;
        private DevExpress.XtraReports.UI.XRTableCell tableCell12;
        private DevExpress.XtraReports.UI.XRTableCell tableCell13;
        private DevExpress.XtraReports.UI.XRTable table2;
        private DevExpress.XtraReports.UI.XRTableRow tableRow4;
        private DevExpress.XtraReports.UI.XRTableRow tableRow5;
        private DevExpress.XtraReports.UI.XRTableCell lblDetailTitle;
        private DevExpress.XtraReports.UI.XRTableCell lblRowNo;
        private DevExpress.XtraReports.UI.XRTableCell lblTrackingNo;
        private DevExpress.XtraReports.UI.XRTableCell lblType;
        private DevExpress.XtraReports.UI.XRTableCell lblExpiryDate;
        private DevExpress.XtraReports.UI.XRTableCell lblPrice;
        private DevExpress.XtraReports.UI.XRTableCell lblPrincipalDebtor;
        private DevExpress.XtraReports.UI.XRTableCell lblEndorser;
        private DevExpress.XtraReports.UI.XRTableCell lblBankAndDeparment;
        private DevExpress.XtraReports.UI.XRTableCell lblDocumentNo;
        private DevExpress.XtraReports.UI.XRTableCell lblAccountNo;
        private DevExpress.DataAccess.ObjectBinding.ObjectDataSource ObjectDataSource;
        private DevExpress.XtraReports.UI.XRTable table4;
        private DevExpress.XtraReports.UI.XRTableRow tableRow7;
        private DevExpress.XtraReports.UI.XRTableCell lblSums;
        private DevExpress.XtraReports.UI.XRTableCell tableCell15;
        private DevExpress.XtraReports.UI.XRTableCell tableCell16;
        private DevExpress.XtraReports.UI.XRPanel panel1;
        private DevExpress.XtraReports.UI.XRLabel lblPersonWhoCollected;
        private DevExpress.XtraReports.UI.XRPageInfo pageInfo1;
    }
}
